### ISSUE TITLE
Cached headers dropped in node > v7.7.x due to api changes

### ISSUE THREAD

**Issue by peteboere** [kwhitley/apicache#94] opened 2017-07-17 08:22 UTC
Node 7.7 introduced some changes to the way http ServerResponse.headers can be manipulated (response._headers appears to have become readonly), so looks like we now have to use the new {set,get,has}Header methods:
https://nodejs.org/api/http.html#http_class_http_serverresponse

Pull request: #91

**Comment by kwhitley** [comment] 2017-07-17 17:58
@peteboere I've merged your PR but tests are failing for me under Node 8 (with restify version 4 or 5 both).  Waiting on https://github.com/restify/node-restify/pull/1409 (fixes an infinite response loop) to be patched through to NPM before I publish, so I can maintain restify support for those guys.  You might want to go and drop a +1 on that thread to help spur them along too!

**Comment by kokarn** [comment] 2017-07-24 20:02
restify/node-restify#1409 is now merged and published as 5.0.1

Could this be fixed as well?
Having issues where misconfigured clients makes the cached response invalid ^^

**Comment by kwhitley** [comment] 2017-07-24 21:16
@peteboere @kokarn Unfortunately little of the restify support is working in my current environment of Node 8.1.3 and node-restify 5.0.1.  It appears they've drastically changed their implementation (not shocking, given the major version change), causing the test suite to fail. 

I need to update the core lib but may have to drop the restify support until this is resolved...

**Comment by kokarn** [comment] 2017-07-24 21:35
Is the test-suite available somewhere?
I'm running it in production right now and apart from the headers seems to be working just fine.
Maybe I can help and/or test.

I do understand that you might want to remove the official restify support tho if it's breaking.
Would you mind publishing the current fix even if you remove the official support? 
At least for me, that's all that's needed.

**Comment by kwhitley** [comment] 2017-07-25 14:04
I understand @kokarn - and if I don't have a solution by the end of the week, that's what I'll do 
- temporarily drop restify support in favor of ensuring continued Node v7, v8 support (I'm on 8 after all)

**Comment by kwhitley** [comment] 2017-08-02 14:24
@svozza Would you mind taking a look at the restify tests and/or implementation to see if we can get these back online with the changes to support Node 7.7+?  I really don't want to cut off support for restify but I don't use the system myself to know enough to get these tests passing...

**Comment by svozza** [comment] 2017-08-02 15:03
Yeah, sure thing. I might not be able to get to it tonight but will try to get to it before the weekend.

**Comment by kwhitley** [comment] 2017-08-02 15:06
Awesome! Thanks so much... I *really* am trying to avoid a major version bump simply because I drop restify support. Totally want a v1 release to have an improved API, flexibility, not to mention written in ES6, etc!

~ Kevin @krwhitley.com
On Wed, Aug 2, 2017 at 10:03 AM, Stefano Vozza <notifications@github.com> wrote:
Yeah, sure thing. I might not be able to get to it tonight but will try to get to it before the weekend.

**Comment by svozza** [comment] 2017-08-02 19:36
So once you upgrade to Restify 5.0 the issue is actually with the Restify eTag plugin we use in the tests. There is an open PR that fixes the problem here: https://github.com/zephrax/restify-etag-cache/pull/19 but I'm not sure when it will be merged. I guess I could fork the repo and apply the fix and we could use that?

**Comment by svozza** [comment] 2017-08-04 08:11
So the eTag plugin PR was merged yesterday, still waiting to hear back about the Restify one.

**Comment by kokarn** [comment] 2017-08-04 08:36
Which is the restify one?

**Comment by svozza** [comment] 2017-08-04 08:37
The second issue I linked to in my message there. It's on the last line of my post.

**Comment by kokarn** [comment] 2017-08-04 08:42
Ah, my bad. Checking on email and the edit didn't go through. Thanks!

**Comment by svozza** [comment] 2017-08-04 08:44
Ah, of course! I mean, if we want we can just point to my fork where's the issue is fixed and use that until Restify merge my PR.

**Comment by kokarn** [comment] 2017-08-04 08:51
That could work but not sure if it's worth it. They have been pretty quick
to merge things in the past.

**Comment by kwhitley** [comment] 2017-08-09 17:40
Also adding you as a collab in NPM @svozza (thanks for all your help!) - may as well have your name slapped onto yet another public package :)

**Comment by kwhitley** [comment] 2017-08-09 17:42
@ ALL : What do you guys think?  Is this all a patch fix (0.8.9) or minor bump (0.9.0)?  It *should* be all backwards compatible I think (only the tests are dependent on specific versions), but there might be minor breaks along the way.

**Comment by kokarn** [comment] 2017-08-09 19:52
Might as well go for 0.9.0 since the 1.0 is coming soon-ish anyways

**Comment by svozza** [comment] 2017-08-10 08:41
> Also adding you as a collab in NPM @svozza (thanks for all your help!) - may as well have your name slapped onto yet another public package :)

Thanks man, this middleware has been a lifesaver for my project in work so it's the least I can do!

**Comment by esarbanis** [comment] 2017-08-16 11:14
@kwhitley when will you be releasing 0.8.8 to npm? I urgently need this fix for my production environment.

**Comment by kwhitley** [comment] 2017-08-17 01:29
Should be solved by release 0.9.0 - go update, everyone! 🍾 

Thanks to all involved, and special thanks to @svozza for chasing down the conflicts upstream in restify itself (to continue restify support for apicache).

**Closed by kwhitley** 2017-08-17 01:29 UTC
Labels: bug, discussion, priority
